---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- name: overview
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Overview
- type: text
  name: title
  label: Title
  config:
    required: true
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- name: project_fg_color
  type: color
  config:
    required: false
    color_format: Hex
  label: Accent color
pages:
- projects/3d-graff.md
- projects/chelsea-landmark.md
- projects/ios-concept.md
- projects/sunk.md
